deadpool: Patch keymint service to replace ndk_platform backend
At the same time bump the ndk version where applicable to fix:

error: module "android.hardware.security.keymint-service.amlogic" variant
"android_vendor_arm_armv8-a": depends on multiple versions of the same aidl_interface:
android.hardware.security.keymint-V1-ndk-source,
android.hardware.security.keymint-V3-ndk-source

Change-Id: I394545d7af4422cae2c446278a681cbbc353c9f3